// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6uvxh0a3wVFjkNFd0A3wNYdMt9y4T3Y',
    appId: '1:255711648674:web:c5a4858095618014a2f0fb',
    messagingSenderId: '255711648674',
    projectId: 'chat-app-fd0d3',
    authDomain: 'chat-app-fd0d3.firebaseapp.com',
    storageBucket: 'chat-app-fd0d3.appspot.com',
    measurementId: 'G-0FDFB5LHTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvINY7TKdJFYYzBTlfns_gEvDZPRFTtFc',
    appId: '1:255711648674:android:6d7d7c5ec82a701ea2f0fb',
    messagingSenderId: '255711648674',
    projectId: 'chat-app-fd0d3',
    storageBucket: 'chat-app-fd0d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yu5hs-FvHfxSs2iJdZUWPmyS0zKv5so',
    appId: '1:255711648674:ios:b896add3bd788e24a2f0fb',
    messagingSenderId: '255711648674',
    projectId: 'chat-app-fd0d3',
    storageBucket: 'chat-app-fd0d3.appspot.com',
    iosBundleId: 'com.example.chatPp',
  );
}
